// <auto-generated />
using System;
using Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222075051_AddAuditLogs")]
    partial class AddAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clean")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DB.DbEmployee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("EmployeeId")
                        .HasName("pk_db_employee");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_db_employee_email");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_db_employee_org_id");

                    b.HasIndex("OrgId", "EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_db_employee_org_id_employee_code");

                    b.ToTable("db_employee", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuAuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("KeyValues")
                        .HasColumnType("text")
                        .HasColumnName("key_values");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("table_name");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("AuditLogId")
                        .HasName("pk_su_audit_log");

                    b.ToTable("su_audit_log", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuMenu", b =>
                {
                    b.Property<Guid>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_code");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_name");

                    b.Property<Guid?>("ParentMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_menu_id");

                    b.Property<string>("Route")
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("MenuId");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("su_menu", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuOrganize", b =>
                {
                    b.Property<Guid>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("org_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("org_code");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("org_name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("OrgId")
                        .HasName("pk_su_organize");

                    b.HasIndex("OrgCode")
                        .IsUnique()
                        .HasDatabaseName("ix_su_organize_org_code");

                    b.ToTable("su_organize", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_code");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("profile_name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("ProfileId")
                        .HasName("pk_su_profile");

                    b.HasIndex("ProfileCode")
                        .IsUnique()
                        .HasDatabaseName("ix_su_profile_profile_code");

                    b.ToTable("su_profile", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuProfileMenu", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("menu_id");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("ProfileId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("su_profile_menu", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_normalized");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_su_user");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_su_user_email_normalized")
                        .HasFilter("email_normalized IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_su_user_employee_id")
                        .HasFilter("employee_id IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_su_user_is_active");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_su_user_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("su_user", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUserOrg", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("UserId", "OrgId")
                        .HasName("pk_su_user_org");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_su_user_org_org_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_su_user_org_default_per_user")
                        .HasFilter("is_default = true");

                    b.ToTable("su_user_org", "clean");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text")
                        .HasColumnName("cr_by");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cr_date");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("upd_by");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upd_date");

                    b.HasKey("UserId", "ProfileId")
                        .HasName("pk_su_user_profile");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_su_user_profile_profile_id");

                    b.ToTable("su_user_profile", "clean");
                });

            modelBuilder.Entity("Domain.Entities.DB.DbEmployee", b =>
                {
                    b.HasOne("Domain.Entities.SU.SuOrganize", "Org")
                        .WithMany("Employees")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_db_employee_su_organize_org_id");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuMenu", b =>
                {
                    b.HasOne("Domain.Entities.SU.SuMenu", "ParentMenu")
                        .WithMany("ChildMenus")
                        .HasForeignKey("ParentMenuId")
                        .HasConstraintName("fk_su_menu_su_menu_parent_menu_temp_id");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuProfileMenu", b =>
                {
                    b.HasOne("Domain.Entities.SU.SuMenu", "Menu")
                        .WithMany("ProfileMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_su_profile_menu_su_menu_menu_temp_id1");

                    b.HasOne("Domain.Entities.SU.SuProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_su_profile_menu_su_profile_profile_id");

                    b.Navigation("Menu");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUser", b =>
                {
                    b.HasOne("Domain.Entities.DB.DbEmployee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entities.SU.SuUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_su_user_db_employee_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUserOrg", b =>
                {
                    b.HasOne("Domain.Entities.SU.SuOrganize", "Org")
                        .WithMany("UserOrgs")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_su_user_org_su_organize_org_id");

                    b.HasOne("Domain.Entities.SU.SuUser", "User")
                        .WithMany("UserOrgs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_su_user_org_su_user_user_id");

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUserProfile", b =>
                {
                    b.HasOne("Domain.Entities.SU.SuProfile", "Profile")
                        .WithMany("UserProfiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_su_user_profile_su_profile_profile_id");

                    b.HasOne("Domain.Entities.SU.SuUser", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_su_user_profile_su_user_user_id");

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.DB.DbEmployee", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuMenu", b =>
                {
                    b.Navigation("ChildMenus");

                    b.Navigation("ProfileMenus");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuOrganize", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("UserOrgs");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuProfile", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("Domain.Entities.SU.SuUser", b =>
                {
                    b.Navigation("UserOrgs");

                    b.Navigation("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
